// Generated by tools/make_data.py – do not edit by hand.

// The check-list: every item is ticked by a photo that holds at least 2 stickers of
// both of its sticker columns (the processor's own rule). The stickers of a column
// are listed top to bottom.
export const MARKER_MM = 35;
export const GROUPS = [
  {
    "id": "sor-2",
    "name": "Bal szekrénysor",
    "items": [
      {
        "id": "sor-2-ajto-1",
        "label": "1. ajtó",
        "canBeEmpty": true,
        "columns": [
          [
            21,
            22,
            23
          ],
          [
            24,
            25,
            26
          ]
        ]
      },
      {
        "id": "sor-2-ajto-2",
        "label": "2. ajtó",
        "canBeEmpty": true,
        "columns": [
          [
            24,
            25,
            26
          ],
          [
            27,
            28,
            29
          ]
        ]
      },
      {
        "id": "sor-2-ajto-3",
        "label": "3. ajtó",
        "canBeEmpty": true,
        "columns": [
          [
            27,
            28,
            29
          ],
          [
            30,
            31,
            32
          ]
        ]
      },
      {
        "id": "sor-2-ajto-4",
        "label": "4. ajtó",
        "canBeEmpty": true,
        "columns": [
          [
            30,
            31,
            32
          ],
          [
            33,
            34,
            35
          ]
        ]
      },
      {
        "id": "sor-2-ajto-5",
        "label": "5. ajtó",
        "canBeEmpty": true,
        "columns": [
          [
            33,
            34,
            35
          ],
          [
            36,
            37,
            38
          ]
        ]
      },
      {
        "id": "sor-2-ajto-6",
        "label": "6. ajtó",
        "canBeEmpty": true,
        "columns": [
          [
            36,
            37,
            38
          ],
          [
            39,
            40,
            41
          ]
        ]
      }
    ]
  },
  {
    "id": "sor-1",
    "name": "Jobb szekrénysor",
    "items": [
      {
        "id": "sor-1-ajto-1",
        "label": "1. ajtó",
        "canBeEmpty": true,
        "columns": [
          [
            0,
            2,
            1
          ],
          [
            3,
            4,
            5
          ]
        ]
      },
      {
        "id": "sor-1-ajto-2",
        "label": "2. ajtó",
        "canBeEmpty": true,
        "columns": [
          [
            3,
            4,
            5
          ],
          [
            6,
            7,
            8
          ]
        ]
      },
      {
        "id": "sor-1-ajto-3",
        "label": "3. ajtó",
        "canBeEmpty": true,
        "columns": [
          [
            6,
            7,
            8
          ],
          [
            9,
            10,
            11
          ]
        ]
      },
      {
        "id": "sor-1-ajto-4",
        "label": "4. ajtó",
        "canBeEmpty": true,
        "columns": [
          [
            9,
            10,
            11
          ],
          [
            12,
            13,
            14
          ]
        ]
      },
      {
        "id": "sor-1-ajto-5",
        "label": "5. ajtó",
        "canBeEmpty": true,
        "columns": [
          [
            12,
            13,
            14
          ],
          [
            15,
            16,
            17
          ]
        ]
      },
      {
        "id": "sor-1-ajto-6",
        "label": "6. ajtó",
        "canBeEmpty": true,
        "columns": [
          [
            15,
            16,
            17
          ],
          [
            18,
            19,
            20
          ]
        ]
      }
    ]
  },
  {
    "id": "parafa-1",
    "name": "Nagy parafatábla",
    "items": [
      {
        "id": "parafa-1-resz-1",
        "label": "1. rész",
        "columns": [
          [
            42,
            43
          ],
          [
            44,
            45
          ]
        ]
      },
      {
        "id": "parafa-1-resz-2",
        "label": "2. rész",
        "columns": [
          [
            44,
            45
          ],
          [
            46,
            47
          ]
        ]
      },
      {
        "id": "parafa-1-resz-3",
        "label": "3. rész",
        "columns": [
          [
            46,
            47
          ],
          [
            48,
            49
          ]
        ]
      }
    ]
  },
  {
    "id": "parafa-2",
    "name": "Kis parafatábla",
    "items": [
      {
        "id": "parafa-2-resz-1",
        "label": "1. rész",
        "columns": [
          [
            50,
            51
          ],
          [
            52,
            53
          ]
        ]
      },
      {
        "id": "parafa-2-resz-2",
        "label": "2. rész",
        "columns": [
          [
            52,
            53
          ],
          [
            54,
            55
          ]
        ]
      }
    ]
  }
];
