"""Generates the data the web app needs from the processor's own files.

    <rmg_tools>/core/.venv/Scripts/python tools/make_data.py <rmg_tools>/core

Writes:
    dictionary.js          the ArUco codes of the dictionary zones.json names
    layout.js              what stands on the wall: the check-list items and their stickers
    tests/fixtures/*       generated "photos" for the detector tests (drawn by code –
                           never a real photo of the wall)

Run it again whenever zones.json gets a new zone or another dictionary.
"""

from __future__ import annotations

import gzip
import json
import sys
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
core = Path(sys.argv[1]).resolve()
sys.path.insert(0, str(core))

from board_worker.zones import KIND_BOARD, load_layout  # noqa: E402
from tests import board_fixtures as fx  # noqa: E402

HEADER = "// Generated by tools/make_data.py – do not edit by hand.\n\n"

# How the wall is shown, left to right (the same order and names as the RMG Tools plugin:
# plugins/bulletin_board/plugin.py – WALL_ROWS, CORK_BOARDS).
GROUPS = [
    ("sor-2", "Bal szekrénysor"),
    ("sor-1", "Jobb szekrénysor"),
    ("parafa-1", "Nagy parafatábla"),
    ("parafa-2", "Kis parafatábla"),
]


def write_dictionary(layout) -> None:
    dictionary = cv2.aruco.getPredefinedDictionary(getattr(cv2.aruco, layout.dictionary))
    codes = []
    for marker in range(len(dictionary.bytesList)):
        cells = cv2.aruco.generateImageMarker(dictionary, marker, 6)[1:5, 1:5] > 127
        codes.append(int("".join("1" if bit else "0" for bit in cells.flatten()), 2))
    body = (
        f"// {layout.dictionary}: one number per sticker id – the 4×4 inner cells, row by row,\n"
        "// first cell = highest bit, 1 = white.\n"
        f"export const DICTIONARY = {json.dumps(codes)};\n"
    )
    (ROOT / "dictionary.js").write_text(HEADER + body, encoding="utf-8", newline="\n")


def write_layout(layout) -> None:
    zones = {zone.id: zone for zone in layout.zones}
    groups = []
    for zone_id, name in GROUPS:
        zone = zones[zone_id]
        items = []
        for door in zone.doors:
            columns = door.sticker_columns
            if zone.kind == KIND_BOARD:
                # A board is photographed part by part: one item per pair of neighbours.
                for index in range(len(columns) - 1):
                    items.append({
                        "id": f"{door.id}-resz-{index + 1}",
                        "label": f"{index + 1}. rész",
                        "columns": [list(columns[index]), list(columns[index + 1])],
                    })
            else:
                items.append({
                    "id": door.id,
                    "label": f"{door.number}. ajtó",
                    "columns": [list(column) for column in columns],
                })
        groups.append({"id": zone_id, "name": name, "items": items})
    body = (
        "// The check-list: every item is ticked by a photo that holds at least 2 stickers of\n"
        "// both of its sticker columns (the processor's own rule).\n"
        f"export const MARKER_MM = {layout.marker_mm:g};\n"
        f"export const GROUPS = {json.dumps(groups, ensure_ascii=False, indent=2)};\n"
    )
    (ROOT / "layout.js").write_text(HEADER + body, encoding="utf-8", newline="\n")


def save_fixture(name: str, photo: np.ndarray, **meta) -> None:
    gray = cv2.cvtColor(photo, cv2.COLOR_BGR2GRAY)
    folder = ROOT / "tests" / "fixtures"
    folder.mkdir(parents=True, exist_ok=True)
    (folder / f"{name}.gray.gz").write_bytes(gzip.compress(gray.tobytes(), 9, mtime=0))
    meta = {"width": gray.shape[1], "height": gray.shape[0], **meta}
    (folder / f"{name}.json").write_text(json.dumps(meta), encoding="utf-8", newline="\n")


def write_fixtures() -> None:
    rng = np.random.default_rng(3)

    def noisy(photo):
        return np.clip(photo + rng.normal(0, 4, photo.shape), 0, 255).astype(np.uint8)

    row = fx.row_canvas()
    save_fixture("door", noisy(fx.photograph(row, fx.DOOR_1, px_per_mm=1.3, skew=0.12)),
                 ids=[0, 1, 2, 3, 4, 5], px_per_mm=1.3)
    save_fixture("door-blurred",
                 noisy(fx.photograph(row, fx.DOOR_1, px_per_mm=1.3, skew=0.12, blur=15)),
                 ids=[0, 1, 2, 3, 4, 5], px_per_mm=1.3)
    save_fixture("two-doors-far", noisy(fx.photograph(row, fx.DOORS_1_2, px_per_mm=0.7)),
                 ids=list(range(9)), px_per_mm=0.7)
    save_fixture("no-stickers", noisy(fx.photograph(row, (60, 100, 330, 900), px_per_mm=1.3)),
                 ids=[], px_per_mm=1.3)

    boards = fx.make_board_layout()
    cork = fx.draw_cork_board(boards, boards.zones[2], {"a": ((100, 100, 210, 297), 1)})
    save_fixture("board-left", noisy(fx.photograph(cork, fx.BOARD_LEFT, px_per_mm=1.1, skew=0.1)),
                 ids=[42, 43, 44, 45], px_per_mm=1.1)

    # Turned photos: a sticker must be found whichever way it is up.
    door = noisy(fx.photograph(row, fx.DOOR_1, px_per_mm=1.3, skew=0.12))
    save_fixture("door-sideways", cv2.rotate(door, cv2.ROTATE_90_CLOCKWISE),
                 ids=[0, 1, 2, 3, 4, 5], px_per_mm=1.3)
    height, width = door.shape[:2]
    turn = cv2.getRotationMatrix2D((width / 2, height / 2), 17, 0.8)
    save_fixture("door-tilted", cv2.warpAffine(door, turn, (width, height), borderValue=(90, 90, 90)),
                 ids=[0, 1, 2, 3, 4, 5], px_per_mm=1.3 * 0.8)


layout = load_layout()
write_dictionary(layout)
write_layout(layout)
write_fixtures()
print("ok")
